### PR TITLE
Add plugin to skip command linker

### PR DESCRIPTION
**Pull request by yathomasi**
By default, our command line linkers always link any inline code based on `dvc`, `cml`, ... our tools. 

If we want to customize them we can always wrap the inline code with a link eg:
```
[`dvc ...`](link)
```

This PR adds a plugin to allow us to have no link at all. For that, we can pass no value. eg:
```
[`dvc ...`]()
```

closes https://github.com/iterative/cml.dev/issues/424

### CODE REVIEW

**Comment by yathomasi** [comment]
> constraining what the auto-linker operates on

We have a constraint on linking when there is inline code with `cml|dvc|...tools` and their subcommand exists or if there is an option we do check if they exist. So, I don't see how we can constrain it more from the auto-linker side. 

Also, we already use links to override the autogenerated links. So, passing an empty value to ignore auto-link seemed a good approach to me.

**Comment by rogermparent** [comment]
> So, I don't see how we can constrain it more from the auto-linker side.

As far as I understand, the originally suggested constraint when this was proposed is

> cml thingy --flag correctly links to /doc/ref/thingy#--flag but cml thingy --flag --another-flag really shouldn't IMO.

It seems to me like auto-linking only code blocks with a single flag would be the most expected, unless there is a good reason to auto-link commands with more than one flag @iterative/docs may be able to think of an example. `[\`link\`]()` feels like it should be more of a last resort on something that would otherwise definitely be linked.

This feature makes sense, but saying that all multi-flag code examples should use it feels a bit kludgy.

**Comment by yathomasi** [comment]
I could only find a similar case scenario in dvc.org 
- https://dvc.org/doc/api-reference/dvcfilesystem#listing-all-dvc-tracked-files-recursively
	-  `dvc ls --recursive --dvc-only`

If we want to fully ignore the command line linker in a similar case scenario then feel free to open a ticket and continue with the discussion.
Personally, I would allow the linker as these are rare and the current solution [`this command will not be linked`]() would allow the skip if we want. 

cc: @iterative/docs

**Comment by jorgeorpinel** [comment]
> I don't really love the solution of adding a remark plugin with new syntax to override the auto-linker instead of constraining what the auto-linker operates

➕ 

See https://github.com/iterative/dvc.org/issues/1614

**Comment by jorgeorpinel** [comment]
> auto-linking only code blocks with a single flag would be the most expected, unless there is a good reason to auto-link commands with more than one flag

OK I guess it's a separate Q from https://github.com/iterative/dvc.org/issues/1614 (that one is more about whether the subcommands and flags actually exist, I suppose. BTW, should we move it to this repo?

To answer the Q, I think a decent default behavior would be to link to the specific option only when there's a single flag indeed, but still link to the general ref. page if there are more (due to ambiguity). Other options:

- Always link to the general page
- Always link to #options if there are flags present

**Comment by yathomasi** [comment]
> BTW, should we move it to this repo?

Sure, we can move it here as core logic is here.

> To answer the Q, I think a decent default behavior would be to link to the specific option only when there's a single flag indeed, but still link to the general ref. page if there are more (due to ambiguity). Other options:
>	- Always link to the general page
>	- Always link to #options if there are flags present

Yes, I agree with this and it works as mentioned except for multiple options. Right now, it links to the first option from the multiple options and ignores anything more. But, as mentioned such usage is rare for us.

**Pull request merged**
